"""phase1_invoices_monitor_state_notification_log

Revision ID: a6a08e11ea74
Revises: 
Create Date: 2026-03-10 08:54:55.976913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a08e11ea74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ksef_number', sa.String(), nullable=False),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('invoice_hash', sa.String(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('form_code', sa.String(), nullable=True),
    sa.Column('issue_date', sa.String(), nullable=True),
    sa.Column('invoicing_date', sa.DateTime(), nullable=True),
    sa.Column('acquisition_date', sa.DateTime(), nullable=True),
    sa.Column('gross_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('vat_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('seller_nip', sa.String(), nullable=False),
    sa.Column('seller_name', sa.String(), nullable=True),
    sa.Column('buyer_nip', sa.String(), nullable=True),
    sa.Column('buyer_name', sa.String(), nullable=True),
    sa.Column('is_self_invoicing', sa.Boolean(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('has_xml', sa.Boolean(), nullable=False),
    sa.Column('has_pdf', sa.Boolean(), nullable=False),
    sa.Column('has_upo', sa.Boolean(), nullable=False),
    sa.Column('xml_path', sa.String(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('upo_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_metadata', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ksef_number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoices_buyer', ['buyer_nip', 'issue_date'], unique=False)
        batch_op.create_index('ix_invoices_date', [sa.literal_column('issue_date DESC')], unique=False)
        batch_op.create_index('ix_invoices_lookup', ['subject_type', 'seller_nip', 'issue_date'], unique=False)
        batch_op.create_index('ix_invoices_type', ['invoice_type'], unique=False)

    op.create_table('monitor_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nip', sa.String(), nullable=False),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=False),
    sa.Column('last_invoice_at', sa.DateTime(), nullable=True),
    sa.Column('last_ksef_number', sa.String(), nullable=True),
    sa.Column('invoices_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_errors', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nip', 'subject_type', name='uq_monitor_nip_subject')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index('ix_notif_dedup', ['dedup_key'], unique=True, sqlite_where=sa.text('dedup_key IS NOT NULL'))
        batch_op.create_index('ix_notif_invoice', ['invoice_id'], unique=False)
        batch_op.create_index('ix_notif_sent', [sa.literal_column('sent_at DESC')], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index('ix_notif_sent')
        batch_op.drop_index('ix_notif_invoice')
        batch_op.drop_index('ix_notif_dedup', sqlite_where=sa.text('dedup_key IS NOT NULL'))

    op.drop_table('notification_log')
    op.drop_table('monitor_state')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index('ix_invoices_type')
        batch_op.drop_index('ix_invoices_lookup')
        batch_op.drop_index('ix_invoices_date')
        batch_op.drop_index('ix_invoices_buyer')

    op.drop_table('invoices')
    # ### end Alembic commands ###
